sequenceDiagram
    participant Client
    participant CSGW as ClientSideGateway
    participant SGGW as ServiceSideGateway
    participant Service

    Client ->> CSGW: Send HTTP Request
    activate CSGW
    note left of CSGW: Locate ServiceSideGateway
    CSGW ->> SGGW: Request in SendRequset package
    SGGW ->> Service: Send HTTP Request
    Service ->> SGGW: HTTP Response
    SGGW ->> CSGW: Response in SendRequest package
    CSGW ->> Client: Send Response
    deactivate CSGW